export const ROUTES = {
    HOME: '',
    ABOUT: '/about-us',
    FAQ: '/faq',
    TAX_SAVER: '/tax-saver',
    SILVER_PLAN: '/silver-plan',
    GOLD_PLAN: '/gold-plan',
    SUPER_TOPUP: '/platinum-plan',
    CART: '/cart',
    CHECKOUT: '/checkout',
    PROFILE: '/profile',
    PAYMENT_DETAILS: '/payment-details/:paymentId',
    RAZORPAY: '/razorpay',
    CONTACT_US: '/contact-us',
    PRODUCTS: '/products',
};
